### ISSUE TITLE
All plural functions are hardcoded into the main build

### ISSUE THREAD

**Issue by artuska** [messageformat/messageformat.js#155]
In 0.2.2 version I was adding language plural functions like that:

```
<script src="messageformat-0.2.2.js"></script>
<script src="messageformat-plural-en.js"></script>
<script src="messageformat-plural-ru.js"></script>
```

Now, in 0.3.1 version `messageformat.js` file has all language plural functions included. Well, why in earth would someone need all language plural functions? This is extra 20 kilobytes of code.

Is there any option to avoid all those bunch of unneeded language plural function be included in the `messageformat.js` build?

**Comment by eemeli** [comment]
The primary intended usage pattern for messageformat.js with browsers is for the strings to be pre-compiled into executable JavaScript, which is then included in a `<script>` tag or otherwise. For convenience, the published version does of course allow itself to be used live in-browser as well, but also for convenience, it bakes in complete language support.

Have you tried precompiled use of the library yet? In addition to the savings in client-side execution time, it'll save you most of the size of the library itself, as the JavaScript output from a JSON object of messageformat strings should only be marginally larger than the input, especially when gzipped.

**Comment by artuska** [comment]
@eemeli I'm using `messageformat` with the `Angular Translate` and there is no options for precompiled translations — `Angular Translate` just takes localization pluralized string (formatted in `messageformat` style) from the JSON file and translates it.

**Comment by artuska** [comment]
Well, I think I can just manually remove unused languages from the `messageformat.js` file. Will try later and report about my genius plan success ;)

**Comment by artuska** [comment]
Well, it worked for me :)
