### ISSUE TITLE
How to translate a list of things (e.g. apples, oranges, and bananas)

### ISSUE THREAD

**Issue by cudasteve** [messageformat/messageformat.js#158]
Forgive me if this is obviously outside of the scope here, but is there (or should there be) a way to handle translation of arbitrary length lists? In english I might say "apples, oranges, and bananas," but I assume in other languages the rules for constructing such lists are likely different. And ideally I'd like to be able to have the translation engine or parser gracefully handle the case when that list becomes "apples and bananas," "grapes, apples, oranges, and bananas," or simply "apples."

I see that there's one extension for offset, but that doesn't meet this need. I'm curious if we could add an extension for this or how that would work.  Maybe something like this?

```
{items, plural, list:and other{,}} ==> "apples, bananas, and oranges"
```

See also: https://github.com/angular-translate/angular-translate/issues/1561

**Comment by rxaviers** [comment]
Maintainers here could give you a better response, but you need a list formatter and then plug its output into your message.

Useful links:
- ecma-402: https://github.com/tc39/ecma402/issues/33
- CLDR: http://unicode.org/reports/tr35/tr35-general.html#ListPatterns
- polyfill: https://github.com/zbraniecki/IntlListFormat

**Comment by cudasteve** [comment]
Thanks @rxaviers that really helps!  So am I understanding that the creation of the list basically needs to be done outside of the messageformat expression and then just injected as one of the variables?  That's what I'm currently thinking I'll need to do by writing my own language-away "grammar" service off to the side.  Something like this?

    var things = ['apples', 'oranges', 'bananas'];
    var numThings = things.length;
    var listOfThings = Grammar.list(things);

The the messageformat would be like this:

    "You bought {numThings, plural, one{something}, other{# things}}: {listOfThings}"

And would output:

    "You bought 3 things: apples, bananas, and oranges"

**Comment by rxaviers** [comment]
Yeap, that's my take on it.

Alternatively, you can "register" your Grammer.list (the list formatter) as a MessageFormat custom formatter. Need to check how to do that though (ref #145, #65)

**Comment by eemeli** [comment]
Sorry for getting to this so late. Somehow had gotten it into my head that getting this to work would be trickier, but it's actually pretty easy. If it's still relevant, here's a formatter that could work; it needs to either hardcode the locale-specific list separators, or use something like `Intl.ListFormat`:

```js
function list(v, lc) {
  const listData = {
    en: { two: ' and ', start: ', ', middle: ', ', end: ', and ' },
    default: { two: ' & ', start: ', ', middle: ', ', end: ', ' }
  }
  if (!Array.isArray(v) || v.length < 2) return v
  lc = lc.replace(/[-_].*/, '')
  const { two, start, middle, end } = listData[lc] || listData.default
  if (v.length === 2) return v[0] + two + v[1]
  let str = v[0] + start + v[1]
  for (let i = 2; i < v.length - 2; ++i) str += middle + v[i]
  return str + end + v[v.length - 1]
}
```

Including the `listData` within the body of the function is recommended for precompiled use, as that'll guarantee it remains within the scope during execution; otherwise you'll need to separately include it in the execution scope. To use, something like this would work:

```js
const MessageFormat = require('messageformat')
const mf = new MessageFormat('en-GB').addFormatters({ list })
const msg = mf.compile('Things: {items, list}')
const items = ['apples', 'bananas', 'oranges']
msg({ items })
// 'Things: apples, bananas, and oranges'
```

**Comment by SlexAxton** [comment]
I wrote a cldr listpattern a week or so ago, fwiw: https://github.com/SlexAxton/listpattern

**Comment by eemeli** [comment]
It'd be great to have a separately-published messageformat list formatter available as a plugin. I split the formatters into separate files, which should make it easier to see how they work.

@SlexAxton do you think you'd have time to put one together for us? It'll need to use the same form as the `number` formatter, so that it gets to read the messageformat instance's list of enabled locales to pick the ones to pull in from the CLDR data.

**Comment by adamcohenrose** [comment]
For anyone looking to use @eemeli's code above (thank you!), there's a bug…

The for loop should go up to `v.length - 1`, not `v.length - 2`:
`for (let i = 2; i < v.length - 1; ++i) str += middle + v[i]`
