### ISSUE TITLE
Ignore improperly formatted statements instead of throwing error

### ISSUE THREAD

**Issue by daveshapiro** [messageformat/messageformat.js#160]
I've added call to messageformat as part of my own existing string.format utility function and I'm getting errors for some content.  One such scenario is when calling the function on dynamically loaded markup with embedded javascript and, in this case, a regex statement such as: "[^A-Z]{4,}".  It seems that messageformat is encountering the {4,}, deciding it has work to do, but failing to parse and throwing a fit.  I can wrap this with a try/catch (as I've done for now), but it probably makes more sense for messageformat to ignore malformed statements.

**Comment by SlexAxton** [comment]
Hmm, I like both situations for different reasons. I prefer error/breakages in dev, but I can see how that's more or less unhelpful in production (as long you can report somehow).

What if we added a hook for these types of errors, and they'll throw errors if you don't register anything, and call your hook if you do. (however, the underlying logic will likely still be a try/catch... if I had to guess)

**Comment by daveshapiro** [comment]
What do you envision being the purpose of the hook?  Would it pass the statement for manual verification or something?

What about an option on either the instance of MessageFormat or the result of compile(): thing.SuppressMalformedStatementErrors = true/false?

Or, assuming there will be other error types:
thing.SuppressErrors(MessageFormat.ErrorTypes.MalformedStatement | ...);

**Comment by daveshapiro** [comment]
Disclaimer: I'm not condoning swallowing errors, simply a means of avoiding having messageformat throw errors under an assumption (ie: "anything using curly braces is my plaything").

**Comment by SlexAxton** [comment]
Oh, I think you should fix (escape in this case) malformed messages. I think the errors help you find out about that, but it isn't worth killing an entire page render for one bad label. The hook would allow you to report breakages back to your servers (via sentry or whatever) without destroying the render of other things.

**Comment by SlexAxton** [comment]
(In other words, "brackets are my playthings" is a hard truth in messageformat, and we probably won't change that since we strive for interoperability with other implementations) ((much like there are reserved characters in other grammars... like your regex))

**Comment by eemeli** [comment]
Fundamentally, it's probably a problem if you're passing a string of input to MessageFormat that has some `{...}` content that should be parsed, and some that should not; swallowing the errors at any point is rather likely to eventually lead to broken output that may be difficult to then detect.

Rather than making it easier to hide the errors, maybe we should make it easier to avoid them? For instance, we probably should provide a method like `MessageFormat.escape()` that'd add the expected `\` prefixes to all `{}#` characters.

Furthermore, we could also consider allowing the start and end delimiters to be optionally doubled, so you'd need to use `{{ mfVar }}` rather than `{ mfVar }`. I'm not quite sure exactly how yet, but the [parser](../../parser/blob/master/parser.pegjs) ought to be modifiable for that. Its current `char` class and/or the `token` class would need to be expanded a bit to allow the un-escaped and un-doubled `{{` and `}}` to pass through.

**Comment by eemeli** [comment]
Closing this as fixed by [`MessageFormat.escape()`](http://messageformat.github.io/messageformat.js/doc/MessageFormat.html#.escape).
