### ISSUE TITLE
How to use custom datetime format in strings?

### ISSUE THREAD

**Issue by maxkoryukov** [messageformat/messageformat.js#162]
Hello!

**Related to messageformat/messageformat.js#19**

I have an ICU-string with ISO8601 format instruction for date:

`Hello, {username}, it is {ts, date} (ISO-timestamp  is {ts, date, YYYY-MM-DDThh:mm:ssZ})`

And I want to get the ISO8601-formatted date in the resulting string (`Hello, Barack Obama, it is Oct 25, 2016 (ISO-timestamp is 2016-10-25T01:01:15Z`).

ICU describes the [SimpleDateFormat](http://userguide.icu-project.org/formatparse/datetime#TOC-SimpleDateFormat), but seems, like this feature is not implemented.

More details on [stackoverflow](http://stackoverflow.com/q/40230467/1115187)

**Comment by maxkoryukov** [comment]
I know, this is issue is very close to the messageformat/messageformat.js/issues/19, but I just want to realize: is the [SimpleDateFormat](http://userguide.icu-project.org/formatparse/datetime#TOC-SimpleDateFormat) described in ICU's specifications an important part of the standard, or no :wink:

**Comment by SlexAxton** [comment]
It is implementable externally if you need to get it in sooner than later (you can extend the simple formatters). I think we'd generally welcome the feature in messageformat but dates are pretty hairy in js, so we've somewhat relied on people doing their own date formatting.

It's not on our shortlist to work on, but we'd be happy to look at some PRs and discuss the implementation.

**Comment by eemeli** [comment]
Here's a quick attempt at this, using messageformat.js [custom formatters](https://messageformat.github.io/guide/#custom-formatters) and [moment.js](http://momentjs.com/):

```js
const moment = require('moment');
const date = (v, lc, fmt) => moment(v).format(fmt || 'MMM D, YYYY');
const mf = new MessageFormat('en').addFormatters({ date });

mf.compile('The date is {D, date}')({ D: '2014-10-01' })
// 'The date is Oct 1, 2014'

mf.compile('The date is {D, date, YYYY-MM-DDThh:mm:ssZ}')({ D: '2014-10-01' })
// 'The date is 2014-10-01T00:00:00+03:00'
```

It's not really perfect, because the parser expects the 3rd param to match the regexp `[0-9a-zA-Z$_][^ \t\n\r,.+={}]*`, so you'd need to prep `fmt` keys for specific formats to use in `date()`, and the moment.js dependency will need to be included separately if you're precompiling the messageformat output.

@SlexAxton, should we consider relaxing the [`functionParams`](/messageformat/parser/blob/master/parser.pegjs#L63) definition to allow for some form of escaped string pass-through? This would probably be another break from the standard, though.

**Comment by maxkoryukov** [comment]
@SlexAxton , @eemeli , thank you, especially for the latest sample of usage;) It is really helpful stuff!
