### ISSUE TITLE
Escaping with backslashes incompatible with ICU MessageFormat

### ISSUE THREAD

**Issue by dvtomas** [messageformat/messageformat.js#171]
Hi,
according to your specs, *"Messageformat.js supports and extends all parts of the standard, with the exception of the deprecated ChoiceFormat."*

According to the standard, *"messageText can contain quoted literal strings including syntax characters. A quoted literal string begins with an ASCII apostrophe and a syntax character (usually a {curly brace}) and continues until the next single apostrophe. A double ASCII apostrohpe inside or outside of a quoted string represents one literal apostrophe."* ...

According to your specs, *"The characters { and } must be escaped with a \ to be included in the output as literal characters. Within plural statements, # must also be similarly escaped. "*

It seems to me, that you have chosen a very different approach to escaping syntax characters than the official standard, even though this fact is not explicitly mentioned anywhere. Thus, your messages are incompatible with the messages written using the standard syntax, making e. g. reusing messages from a webapp java backend (validation messages etc.) and javascript frontend impossible, is that correct? Is there perhaps a toggle to make your messageformat process the messages according to the official standard? Or, perhaps, is there some js conversion function that would take the standard formatted message and turn it into message suitable for processing by your implementation?

I know that the original apostrophe escaping was a stupid decision, but it's a standard nonetheless. I hope there's a way to make your promising looking library work with the standard format.

**Comment by eemeli** [comment]
The one strictness toggle we've currently got is [setStrictNumberSign](http://messageformat.github.io/messageformat.js/doc/MessageFormat.html#setStrictNumberSign), and we should add to that if there's another way we're breaking the standard.

Would you have an example messageText string available that we're not parsing according to the standard? It's been a while since we've needed to do any changes to the parser, so I at least don't recall of the top of my head whether this will require changes to the [PEG.js parser](https://github.com/messageformat/parser/blob/master/parser.pegjs), or just in how its output is handled.

**Comment by dvtomas** [comment]
Yes, one example, simplified from your very own escaping docs:

```"{S, plural, other{# is a \\#}}"``` expands with standard version to ```5 is a \5``` because the standard doesn't treat backslashes specially. Your implementation expands to ```5 is a #```, though.

I'm not sure if you honor quoting using apostrophes. If you do, which ```ApostropheMode``` (see http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessagePattern.ApostropheMode.html ) do you use?

**Comment by dvtomas** [comment]
Hmm, it seems that https://www.npmjs.com/package/message-format adheres to the standard better, will explore...

**Comment by eemeli** [comment]
With messageformat/parser#3 we can now quote/escape with apostrophes using `DOUBLE_OPTIONAL` mode (thanks to @nkovacs). That's not released yet as it'll need a major version upgrade; hence the 2.0 milestone on this.

While we're at that, I think we should reconsider our use of backslash for escaping `#{}` characters. @SlexAxton, thoughts? I think we've three options here:
1. Keep `\` escaping as-is
2. Add a toggle to either disable or enable it
3. Remove it completely, leaving only `'#'`-style escaping.

I'm tending towards the third option due to its simplicity, with the caveat that we could/should then parse the input strings for possible conflicts and `console.warn` the user about it. Keeping two escaping methods is not Right, and I'd rather not add yet another toggle to the parser.

**Comment by SlexAxton** [comment]
This feels like something that could break a lot of old code. My preference would be to only have the option to do it the right way (which is uglier imo, but interop with java is nice and escapes are decently uncommon) but possibly also link to a gist/codemod that'll convert the old escapes to the new ones. All with a major version bump of course.

**Comment by eemeli** [comment]
Ping @SlexAxton, this is probably the only remaining undecided possibly breaking change to include in the v2 release that's come up so far. I think I concur with the option-3 route of removing `\` escapes, if you're still agreed that's the way to go? Started working on a codemod for this today; as it turns out I needed to write [`json-estree-ast`](/eemeli/json-estree-ast) to make it even possible as jscodeshift didn't support JSON input.
