### ISSUE TITLE
How to handle special language grammar like russian

### ISSUE THREAD

**Issue by krysalead** [messageformat/messageformat.js#174]
Hi,

Thanks for the lib, very useful but we have an issue with the russian language
1 день
2 - 4 дня
5 - 20 дней
21 день
22 – 24 дня
25 – 30 дней
31 день
32 – 34 дня
35 – 40 дней
There is more than a simple case of plural and singular version
Do you know how this can be handled with your library?

Thanks & regards

**Comment by SlexAxton** [comment]
That's the core use case for MessageFormat. MessageFormat uses the plural forms as described by the CLDR in order to map number values to plural keywords. Russian has 4 plural keys: `one`, `few`, `many`, and `other`.

Here's the CLDR entry: http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#ru

So any time you needed to write a sentence that had pluralization, you'd need to include a branch for each keyword.

`There {count, plural, one{is 1 result} few{are # results} many{are # results} other{are # results}.`

That looks a bit silly in English but it should make sense in Russian, if you consider the numbers that map to those keywords.

Hope that helps!

**Comment by krysalead** [comment]
Thanks a lot indeed it helps

**Comment by maxkoryukov** [comment]
Russian example (for google-search, and guys, who will find this issue later):

`В итоге {count, plural, one{найден # результат} few{найдено # результата} many{найдено # результатов} other{найдено # результата}}.`

@krysalead, Probably, problem solved, issue could be closed.

**Comment by SlexAxton** [comment]
Thanks @maxkoryukov !
